import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { cn } from "@/lib/utils";

import { TRPCReactProvider } from "@/trpc/client";

import { Toaster } from "@/components/ui/sonner";

import { DropdownProvider } from "@/providers/dropdown-provider";

import "./globals.css";
import { ModalProvider } from "@/providers/modals-provider";
import { ThemeProvider } from "@/providers/theme-provider";

const font = Inter({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className, "antialiased h-screen")}>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
            storageKey="opal-theme"
          >
            <TRPCReactProvider>
              <DropdownProvider>
                {children}
                <ModalProvider />
                <Toaster richColors position="top-center" />
              </DropdownProvider>
            </TRPCReactProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
