import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { cn } from "@/lib/utils";

import { TRPCReactProvider } from "@/trpc/client";

import { Toaster } from "@/components/ui/sonner";

import { DropdownProvider } from "@/providers/dropdown-provider";

import "./globals.css";
import { ModalProvider } from "@/providers/modals-provider";

const font = Inter({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body className={cn(font.className, "antialiased h-screen")}>
          <TRPCReactProvider>
            <DropdownProvider>
              {children}
              <ModalProvider />
              <Toaster richColors position="top-center" />
            </DropdownProvider>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
